services:
  backend:
    image: ghcr.io/shinrai06/proj-mgmt-backend:latest
    container_name: proj_mgmt-backend
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    # depends_on:
    #   - mongo
    restart: unless-stopped

#   mongo:
#     image: mongo:6
#     environment:
#       MONGO_INITDB_DATABASE: teamsync_db
#     volumes:
#       - mongo_data:/data/db
#     ports:
#       - "27017:27017"
#     restart: unless-stopped

# volumes:
#   mongo_data:

